### ISSUE TITLE
Custom Icon needed

### ISSUE THREAD

**Issue by troglodyne** [cpanelsky/MailAccountManager#2]
Looks like this re-uses an icon already shipped with WHM (and probably covered under the licensing terms thereof). You may _need_ to replace this to comply with licensing terms of cPanel & WHM.

Having a custom icon would also help distinguish the feature.

**Comment by cpanelsky** [comment]
Hehe, it's all cPanel owned =) 

I got a custom(ish? =] ) icon put in now though.

**Comment by troglodyne** [comment]
Seems fine to me, certainly looks distinct.
