### ISSUE TITLE
Fix a few issues with rpmbuild process

### ISSUE THREAD

**Issue by troglodyne** [cpanelsky/MailAccountManager#5]
Ran rpmbuild --define '%_topdir /opt/MailAccountManager/rpmbuild' -ba rpmbuild/SPECS/MailAccountManager.spec
(as I figured that'd be the easiest way to verify whether this thing builds properly).

The rpmbuild process _installed_ the plugin for me, which was somewhat odd. The RPM installation process itself should do that. Similarly, when actually installing the RPM (that is currently in the toplevel of the repo), it was blank per yum (would take up 0.0mb of space).

I think I'll add a rpm build instruction file and tweak the specfile a bit, see if I can't get it to work right proper.

**Comment by cpanelsky** [comment]
Definitely some issues, I had the first builds dir schema off, so I scrapped it completely and then cobbled this together at a minimum just to get it switched over to an RPM.
